### ISSUE TITLE
[Bug Report]: Topic creations doesn't seem to work with only the name

### ISSUE THREAD

**Issue by jdaaboul** [Azure/bicep-registry-modules#726] opened 2023-12-13 20:12 UTC
### Module path

service-bus/namespace

### Bicep version

0.23.1

### Describe the bug

Topic creation doesn't seem to work with minimum parameters

### To reproduce

Try to create topics within a service bus namespace with only the minimum parameters

### Code snippet

```Bicep
var queues = [ 'admin.commands', 'trial.commands', 'tenant.commands', 'frontend.commands' ]
var topics = [
  {
    name: 'machin'
  }
  {
    name: 'frontend.events'
    subscriptions: [ 'frontend' ]
  }
  {
    name: 'trial.events'
    subscriptions: [ 'admin', 'trial', 'frontend' ]
  }
  {
    name: 'legacy.events'
    subscriptions: [ 'tenant', 'trial' ]
  }
  {
    name: 'tenant.events'
    subscriptions: [
      'admin'
      'tenant'
      'trial'
      'frontend'
    ]
  }
  {
    name: 'admin.events'
    subscriptions: [ 'admin', 'frontend' ]
  }
  {
    name: 'data.events'
    subscriptions: [ 'frontend' ]
  }
]
module namespace 'br/public:avm/res/service-bus/namespace:0.1.0' = {
  name: 'service-bus-namespace'
  params: {
    // Required parameters
    name: 'sb-test-dev-1'
    skuObject: {
      name: 'Standard'
    }
    // Non-required parameters
    location: location
    queues: [for queue in queues: {
      name: queue
    }]

    topics: [for topic in topics: {
      name: topic.name
    }]
  }
}
```

### Relevant log output

```Shell
SubCode=40000. Bad Request. To know more visit https://aka.ms/sbResourceMgrExceptions. . TrackingId:af0661ed-9fca-429d-8185-e17c96e3cd49_G31, SystemTracker:sb-joseph-mtm-dev-1.servicebus.windows.net:machin, Timestamp:2023-12-13T20:03:44 (Code: MessagingGatewayBadRequest)
```

**Comment by AlexanderSehr** [comment] 2023-12-19 20:17
Hey @jdaaboul ,
I just assigned @ChrisSidebotham as he is the owner of the module.
Upon first review I did not see any obvious issue, so we need to reproduce the issue for troubleshooting.

**Comment by ChrisSidebotham** [comment] 2023-12-20 13:09
Hi @jdaaboul,

Thanks for raising this issue. I will look in to running a test with your supplied code and respond back here with my findings. Firstly I would like to draw your attention to the current configuration you have;
```
topic: [
 {
  {
    name: 'frontend.events'
    subscriptions: [ 'frontend' ]
  }
 }
]
```
`subscriptions` is currently not support for the current version of the service bus module and is in development which is being tracked under this issue: #722

**Comment by ChrisSidebotham** [comment] 2023-12-20 16:53
@jdaaboul - The issue has been found within the child module for `topics` this is due to parameters being passed which the RP does not allow outside of premium sku. a task has been added to the issue #722 and a fix will be included in the next update

**Closed** 2023-12-21 21:31 UTC
Labels: Bug Report, Type: AVM :a: :v: :m:, Status: In PR :point_right:, Class: Resource Module :package:
