### ISSUE TITLE
[Feature Request]: Add Firewall Rules to `synapse/workspace`

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#2372] opened 2024-02-06 15:15 UTC
### Description

I'd like to request that firewall rules be created alongside synapse workspace module. 

('Microsoft.Synapse/workspaces/firewallRules@2021-06-01')

**Comment by AlexanderSehr** [comment] 2024-06-14 13:40
Migrated the issue from CARML. Please note that the module is currently orphaned (ref: https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/)

**Comment by Ralph101** [comment] 2024-06-27 06:11
Should be solved in this linked PR: #1189

**Comment by AlexanderSehr** [comment] 2024-07-11 18:57
Closing as duplicate of #1189

**Closed by AlexanderSehr** 2024-07-11 18:57 UTC
Labels: Needs: Triage :mag:, Type: AVM :a: :v: :m:, Needs: Immediate Attention :bangbang:, Needs: Module Owner :mega:, Status: Module Orphaned :eyes:, Status: Response Overdue :triangular_flag_on_post:, Class: Resource Module :package:
