### ISSUE TITLE
[AVM Module Issue]: can no longer provision a sqlserver without audit settings always being configured

### ISSUE THREAD

**Issue by christianacca** [Azure/bicep-registry-modules#3888] opened 2024-12-05 13:54 UTC
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/sql/server

### (Optional) Module Version

latest (0.11.1)

### Description

As of this commit: https://github.com/Azure/bicep-registry-modules/commit/d26fc144f5df0652b0cb954a7b05ad7c81648df8 to `avm/res/sql/server`, it's no longer possible to provision an sqlserver _without_ auditing settings also being configured.

The best you can do is to provision with audit settings in a disabled state.

Take for example: NOT supplying `auditSettings` or using `auditSettings: null` in the module's params list results in auditing settings being configured with a default state of enabled

The only option is to provision the server with auditing configured, but in with a state of disabled. EG `auditSettings: { state: 'Disabled' }`

**Comment by peterbud** [comment] 2024-12-05 15:00
Hi @christianacca , thanks for the feedback.

This audit settings was a result of a longer discussion with the team on what should be the the default etc., Here you can see the details: https://github.com/Azure/bicep-registry-modules/pull/3582#issuecomment-2426261161

So based on that I'd say currently this is not an issue, but by design behaves like this, primarily to follow Azure security recommendations.

Also it would be great to hear if having a disabled audit settings is causing problems, if you really don't want to turn it on?

**Comment by christianacca** [comment] 2024-12-05 15:55
@peterbud thanks for reply.

OK so I'm happy to use `auditSettings: { state: 'Disabled' }` if you reckon there is no implications to having audit settings enabled with default values but with the state set to disabled.

That's what you're saying right - there shouldn't be any "side-effect" or change in behaviour?

**Comment by peterbud** [comment] 2024-12-06 17:14
After more discussions, I believe I'll add a new parameter to disable AuditSettings if you want to opt-out completely.

**Comment by christianacca** [comment] 2024-12-06 18:18
Interesting. I've set `auditSettings: { state: 'Disabled' }` and get this:

![Image](https://github.com/user-attachments/assets/683456ec-8e01-41a3-8abf-ed7156ea2b42)

So it seems a benign param. I'll probably use the new "disable audit settings" parameter when it comes available, as it would seems to make intent a little more clearer.

Thanks for looking into this. Do you want me to close issue now or do you want to leave open and close it with the future PR?

**Comment by peterbud** [comment] 2024-12-06 21:51
Just keep it open until the PR will be merged

**Closed** 2024-12-21 17:22 UTC
Labels: Type: AVM :a: :v: :m:, Type: Question/Feedback :raising_hand:, Class: Resource Module :package:, Language: Bicep :muscle:
