### ISSUE TITLE
[AVM Module Issue]:  osDisk required properties for diskSizeGB and storageAccountType issues.

### ISSUE THREAD

**Issue by darrenFrowen** [Azure/bicep-registry-modules#2082] opened 2024-05-28 15:07 UTC
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.4.2

### Description

Hi,

I have an existing resource template for Virtual Machine that is an Market place Checkpoint NVA. This does not require diskSizeGB and storageAccountType and as far as i am aware comes via the custom Checkpoint Market place image. Can these two properties be optional?

Regards

**Comment by AlexanderSehr** [comment] 2024-06-04 07:00
Hey @rahalan, please take a look at your earliest convenience and triage the issue💪

**Comment by rahalan** [comment] 2024-06-04 14:45
@darrenFrowen thank you. Will investigate

**Comment by rahalan** [comment] 2024-06-07 15:52
@darrenFrowen after reading the whole thread, it seems the issue is solved. Correct?

**Comment by darrenFrowen** [comment] 2024-06-07 18:14
Hi,Yes this one can be closed thank youOn 7 Jun 2024, at 16:52, Rainer Halanek ***@***.***> wrote:﻿
@darrenFrowen after reading the whole thread, it seems the issue is solved. Correct?

**Comment by danycontre** [comment] 2024-06-11 21:29
@rahalan @AlexanderSehr can this item be reopened or should i submit a new one?

Having the same issue trying to deploy a VM without providing a value for osdisk.diskSizeGB, we don't want to override the setting from the image, but the module is enforcing us to provide a value for diskSizeGB.

Context: we are refactoring AVD LZA code to migrate from CARML to AVM.

**Comment by rahalan** [comment] 2024-06-12 09:59
@danycontre Thank you, issue is still open. I will look into it

**Comment by rahalan** [comment] 2024-07-03 15:26
@danycontre will be fixed with PR #2616

**Closed** 2024-07-03 21:03 UTC
Labels: Type: AVM :a: :v: :m:, Class: Resource Module :package:

**Comment by darrenFrowen** [comment] 2024-07-04 10:36
Thank you, confirmed now working version 0.5.2 using null value.

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/cc20dae2-6e85-446c-8157-ba5878d7aa58)
