### ISSUE TITLE
[AVM Module Issue]: Make hub-virtual-network-connection a top level resource

### ISSUE THREAD

**Issue by HexagonSam** [Azure/bicep-registry-modules#3119] opened 2024-08-29 21:49 UTC
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/virtual-hub

### Description

I have a requirement for attaching new virtual networks to an existing virtual-hub. The current sub-module hub-virtual-network-connection is not available seperately to deploy this resource, and is only available when deploying a virtual-hub directly (at least as far as I can determine).

**Comment by AlexanderSehr** [comment] 2024-09-04 18:07
Hey @HexagonSam,
this issue will unfortunately join a pool of several other, very similar, issues that request the child-modules to be published:
- https://github.com/Azure/bicep-registry-modules/issues/1390
- https://github.com/Azure/bicep-registry-modules/issues/1933
- https://github.com/Azure/bicep-registry-modules/issues/2899
- https://github.com/Azure/Azure-Verified-Modules/issues/578
- https://github.com/Azure/Azure-Verified-Modules/issues/747

The short of it is that we the way the module's are structured is so by design to align with the ProviderNamespace-ResourceType structure of ARM. Much of the CI and processes are designed around that, with the clear goal of eventually enabling the publishing of child-modules again (which are tested through their parent) - just as it is done in the [CARML - CI](https://github.com/Azure/ResourceModules). 
I already described in a few places why it is not a straight forward solution to implement as it's effectively made very hard by a manual process we have no control over - but I really hope we can get this sorted rather sooner than later.

That said, by mentioning the other issues in this comment, this issue is effectively now connected to them so that we can easily find it again. For this issue in particular that means however that I'll close it not as closed (because it isn't), but as 'not planned' (even though that's also not entirely accurate). We have an internal backlog item to track progress on this where it will be tracked going forward.

Sorry for not having better news to offer :-/ For the time being, for connections specifically, you'd need to deploy them through the hub module, or by using a copy of the module, or by implementing the raw bicep code.

**Closed by AlexanderSehr** 2024-09-04 18:07 UTC
Labels: Type: AVM :a: :v: :m:, Type: Feature Request :heavy_plus_sign:, Class: Resource Module :package:
