### ISSUE TITLE
[AVM CI Environment Issue]:  Add AVM Static Validation Test To Ensure `enableTelemetry` is always passed to any called AVM modules (exc. Utility Modules)

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#3504] opened 2024-10-10 15:16 UTC
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Add AVM Static Validation Test To Ensure `enableTelemetry` is always passed to any called AVM modules (exc. Utility Modules)

- [x] Also add to the Specification - @ReneHezser is handling update SFR4 as we speak

**Comment by ReneHezser** [comment] 2024-10-10 16:22
PR is open https://github.com/Azure/Azure-Verified-Modules/pull/1519

**Comment by eriqua** [comment] 2024-10-15 22:53
@jtracey93 @AlexanderSehr @ReneHezser this looks a duplicate of #2977 
Would you agree to close it?

**Comment by jtracey93** [comment] 2024-10-16 09:01
it is, but PR is in, so we should be able to close both soon

**Comment by jtracey93** [comment] 2024-10-16 09:02
Ah actually the PR does not include a test . Happy for you to close whichever one you see fit to do so

**Comment by AlexanderSehr** [comment] 2024-10-16 19:20
Closing this one as the other has a bit more detail + we should not fundamentally exclude utility modules - but only exclude modules that, in general, don't implement the telemetry parameter. Reason being: If a utility module uses a deployment script - it would actually implement our telemetry deployment 😉

**Closed by AlexanderSehr** 2024-10-16 19:20 UTC
Labels: Type: AVM :a: :v: :m:, Type: Feature Request :heavy_plus_sign:, Needs: Core Team :genie:, Type: CI :rocket:
